[package]
name = "base62"
version = "2.0.0"
authors = [
    "François Bernier <frankbernier@gmail.com>",
    "Chai T. Rex <ChaiTRex@users.noreply.github.com>",
    "Kevin Darlington <kevin@outroot.com>",
    "Christopher Tarquini <code@tarq.io>",
]
edition = "2018"
description = "A Base62 encoding/decoding library"
documentation = "https://docs.rs/base62/"
homepage = "https://github.com/fbernier/base62"
repository = "https://github.com/fbernier/base62"
readme = "README.md"
keywords = ["base62", "encoding", "decoding", "url", "shortener"]
license = "MIT"
exclude = [
    ".github/*",
]

[dev-dependencies]
quickcheck = "1"
criterion = "0.3.5"

[[bench]]
name = "base62"
harness = false
